// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7CBKllwWDpNR5VakSLCQeVUjA2U944qo',
    appId: '1:394735091327:web:eeab8f3a01890a7d02894a',
    messagingSenderId: '394735091327',
    projectId: 'fcmtest-328f7',
    authDomain: 'fcmtest-328f7.firebaseapp.com',
    storageBucket: 'fcmtest-328f7.appspot.com',
    measurementId: 'G-HW4PD3R2PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhyQ_ae2qbvYjIkqpieBxhyDmbQLweFYc',
    appId: '1:394735091327:android:b84a2b7aec5e92ec02894a',
    messagingSenderId: '394735091327',
    projectId: 'fcmtest-328f7',
    storageBucket: 'fcmtest-328f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBugx4bpat-U0YjaBxqC5zVqfSz8pgxgoU',
    appId: '1:394735091327:ios:ab89b95737fe490302894a',
    messagingSenderId: '394735091327',
    projectId: 'fcmtest-328f7',
    storageBucket: 'fcmtest-328f7.appspot.com',
    iosClientId: '394735091327-5uugq49boogecu474i9f9r37bs1v7210.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBugx4bpat-U0YjaBxqC5zVqfSz8pgxgoU',
    appId: '1:394735091327:ios:ab89b95737fe490302894a',
    messagingSenderId: '394735091327',
    projectId: 'fcmtest-328f7',
    storageBucket: 'fcmtest-328f7.appspot.com',
    iosClientId: '394735091327-5uugq49boogecu474i9f9r37bs1v7210.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmtest',
  );
}
